#!/bin/bash

# lib/html_report.sh - HTML Report Generator
# Generates a self-contained, styled HTML report

generate_html_report() {
    local target=$1
    local timestamp=$2
    local combined_file=$3
    local duration=$4
    local html_file="$OUTPUT_DIR/${target}_report_${timestamp}.html"
    
    local total=$(wc -l < "$combined_file" 2>/dev/null || echo 0)
    
    log_info "Generating HTML report..."
    
    cat <<'HEADER' > "$html_file"
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SerphunterRecon - Scan Report</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Segoe UI', sans-serif; background: #0d1117; color: #c9d1d9; }
        .container { max-width: 900px; margin: 0 auto; padding: 20px; }
        .header { background: linear-gradient(135deg, #1a1b27, #2d333b); padding: 30px;
                   border-radius: 12px; margin-bottom: 20px; border: 1px solid #30363d; }
        .header h1 { color: #58a6ff; font-size: 24px; }
        .header p { color: #8b949e; margin-top: 8px; }
        .stats { display: grid; grid-template-columns: repeat(3, 1fr); gap: 15px; margin: 20px 0; }
        .stat-card { background: #161b22; padding: 20px; border-radius: 10px;
                     border: 1px solid #30363d; text-align: center; }
        .stat-card .number { font-size: 32px; font-weight: bold; color: #58a6ff; }
        .stat-card .label { color: #8b949e; font-size: 14px; margin-top: 5px; }
        .results { background: #161b22; border-radius: 10px; padding: 20px;
                   border: 1px solid #30363d; margin-top: 20px; }
        .results h2 { color: #58a6ff; margin-bottom: 15px; }
        .subdomain { padding: 8px 12px; border-bottom: 1px solid #21262d;
                     font-family: monospace; font-size: 14px; }
        .subdomain:hover { background: #1c2128; }
        .footer { text-align: center; color: #484f58; margin-top: 30px; font-size: 12px; }
    </style>
</head>
<body>
<div class="container">
HEADER

    # Header section
    cat <<EOF >> "$html_file"
    <div class="header">
        <h1>🔍 SerphunterRecon - Scan Report</h1>
        <p>Target: <strong>$target</strong> | Generated: $(date)</p>
    </div>
    
    <div class="stats">
        <div class="stat-card">
            <div class="number">$total</div>
            <div class="label">Subdomains Found</div>
        </div>
        <div class="stat-card">
            <div class="number">${duration}s</div>
            <div class="label">Scan Duration</div>
        </div>
        <div class="stat-card">
            <div class="number">$(ls "${BASE_OUTPUT_DIR:-$OUTPUT_DIR}/${target}/sources"/${target}_*_${timestamp}.txt 2>/dev/null | wc -l)</div>
            <div class="label">Sources Queried</div>
        </div>
    </div>
    
    <div class="results">
        <h2>Discovered Subdomains</h2>
EOF

    # Add each subdomain
    while IFS= read -r subdomain; do
        [[ -z "$subdomain" ]] && continue
        echo "        <div class=\"subdomain\">$subdomain</div>" >> "$html_file"
    done < "$combined_file"

    cat <<'FOOTER' >> "$html_file"
    </div>
    <div class="footer">
        <p>Generated by SerphunterRecon v1.5 | For authorized security testing only</p>
    </div>
</div>
</body>
</html>
FOOTER

    log_success "HTML report saved to: $html_file"
}
